import type { VrtMaskRule, VrtPlatform, VrtSceneRef, VrtTheme, VrtViewport } from './types';

export type VrtCatalogMeta = VrtSceneRef;

function meta(
  id: string,
  journey: string,
  screen: string,
  state: string,
  mask: readonly VrtMaskRule[] = [],
): VrtCatalogMeta {
  return Object.freeze({
    id,
    journey,
    screen,
    platform: 'all' as VrtPlatform | 'all',
    viewport: 'all' as VrtViewport | 'all',
    theme: 'dark' as VrtTheme,
    state,
    mask: Object.freeze(mask) as readonly VrtMaskRule[],
  });
}

const pubkyMask = Object.freeze({ testID: 'mask-pubky', reason: 'pubky' as const });
const authUrlMask = Object.freeze({ testID: 'mask-auth-url', reason: 'secret' as const });
const recoveryMask = Object.freeze({ testID: 'mask-recovery', reason: 'recovery' as const });

export const VRT_CATALOG_META: readonly VrtCatalogMeta[] = Object.freeze([
  meta('design-system.token-swatch.default', 'design-system', 'token-swatch', 'default'),
  meta('bootstrap.app-splash.loading', 'bootstrap', 'app-splash', 'loading'),
  meta('bootstrap.linking-fallback.loading', 'bootstrap', 'linking-fallback', 'loading'),
  meta('auth.welcome.idle', 'auth', 'welcome', 'idle'),
  meta('auth.welcome.loading', 'auth', 'welcome', 'loading'),
  meta('auth.welcome.error', 'auth', 'welcome', 'error'),
  meta('auth.welcome.debug-empty', 'auth', 'welcome', 'debug-empty'),
  meta('auth.welcome.debug-busy', 'auth', 'welcome', 'debug-busy'),
  meta('auth.welcome.debug-error', 'auth', 'welcome', 'debug-error'),
  meta('auth.welcome.debug-result', 'auth', 'welcome', 'debug-result'),
  meta('auth.awaiting-ring.with-url', 'auth', 'awaiting-ring', 'with-url', [authUrlMask]),
  meta('auth.awaiting-ring.waiting', 'auth', 'awaiting-ring', 'waiting'),
  meta('auth.awaiting-ring.copied', 'auth', 'awaiting-ring', 'copied'),
  meta('auth.awaiting-ring.fail', 'auth', 'awaiting-ring', 'fail'),
  meta('auth.enable.checking', 'auth', 'enable', 'checking'),
  meta('auth.enable.native-missing', 'auth', 'enable', 'native-missing'),
  meta('auth.enable.enabled', 'auth', 'enable', 'enabled'),
  meta('auth.enable.session-offline', 'auth', 'enable', 'session-offline'),
  meta('auth.enable.authorizing', 'auth', 'enable', 'authorizing', [authUrlMask]),
  meta('auth.enable.authorizing-https', 'auth', 'enable', 'authorizing-https', [authUrlMask]),
  meta('auth.enable.success', 'auth', 'enable', 'success'),
  meta('auth.enable.error', 'auth', 'enable', 'error'),
  meta('tabs.chats.messaging-off', 'tabs', 'chats', 'messaging-off'),
  meta('tabs.chats.empty', 'tabs', 'chats', 'empty'),
  meta('tabs.chats.populated', 'tabs', 'chats', 'populated', [pubkyMask]),
  meta('tabs.chats.unread-99', 'tabs', 'chats', 'unread-99'),
  meta('tabs.chats.pending-badge', 'tabs', 'chats', 'pending-badge'),
  meta('tabs.chats.offline', 'tabs', 'chats', 'offline'),
  meta('tabs.channels.empty', 'tabs', 'channels', 'empty'),
  meta('tabs.channels.populated', 'tabs', 'channels', 'populated', [pubkyMask]),
  meta('tabs.channels.create-private', 'tabs', 'channels', 'create-private'),
  meta('tabs.channels.create-public', 'tabs', 'channels', 'create-public'),
  meta('tabs.channels.join-empty', 'tabs', 'channels', 'join-empty'),
  meta('tabs.channels.join-invalid', 'tabs', 'channels', 'join-invalid'),
  meta('tabs.channels.join-busy', 'tabs', 'channels', 'join-busy'),
  meta('stack.channel.loading', 'stack', 'channel', 'loading'),
  meta('stack.channel.empty', 'stack', 'channel', 'empty'),
  meta('stack.channel.populated', 'stack', 'channel', 'populated', [pubkyMask]),
  meta('stack.channel.deleted', 'stack', 'channel', 'deleted'),
  meta('stack.channel.reply', 'stack', 'channel', 'reply'),
  meta('stack.channel.reactions', 'stack', 'channel', 'reactions'),
  meta('stack.channel.membership', 'stack', 'channel', 'membership'),
  meta('stack.channel.composer-hidden', 'stack', 'channel', 'composer-hidden'),
  meta('stack.channel.public', 'stack', 'channel', 'public'),
  meta('stack.channel-members.list', 'stack', 'channel-members', 'list', [pubkyMask]),
  meta('stack.channel-members.admin-add', 'stack', 'channel-members', 'admin-add', [pubkyMask]),
  meta('stack.channel-members.leave', 'stack', 'channel-members', 'leave', [pubkyMask]),
  meta('stack.channel-members.left', 'stack', 'channel-members', 'left', [pubkyMask]),
  meta('stack.channel-members.public-refresh', 'stack', 'channel-members', 'public-refresh', [pubkyMask]),
  meta('tabs.contacts.empty', 'tabs', 'contacts', 'empty', [pubkyMask]),
  meta('tabs.contacts.populated', 'tabs', 'contacts', 'populated', [pubkyMask]),
  meta('tabs.contacts.syncing', 'tabs', 'contacts', 'syncing', [pubkyMask]),
  meta('tabs.contacts.nexus-note', 'tabs', 'contacts', 'nexus-note', [pubkyMask]),
  meta('tabs.contacts.offline', 'tabs', 'contacts', 'offline', [pubkyMask]),
  meta('stack.contact-search.empty', 'stack', 'contact-search', 'empty', [pubkyMask]),
  meta('stack.contact-search.invalid', 'stack', 'contact-search', 'invalid', [pubkyMask]),
  meta('stack.contact-search.valid', 'stack', 'contact-search', 'valid', [pubkyMask]),
  meta('stack.contact-search.loading', 'stack', 'contact-search', 'loading', [pubkyMask]),
  meta('stack.contact-search.not-found', 'stack', 'contact-search', 'not-found', [pubkyMask]),
  meta('stack.contact-search.added', 'stack', 'contact-search', 'added', [pubkyMask]),
  meta('stack.contact-search.qr', 'stack', 'contact-search', 'qr', [pubkyMask]),
  meta('stack.contact-detail.default', 'stack', 'contact-detail', 'default', [pubkyMask]),
  meta('tabs.profile.unnamed', 'tabs', 'profile', 'unnamed', [pubkyMask]),
  meta('tabs.profile.with-pubky', 'tabs', 'profile', 'with-pubky', [pubkyMask]),
  meta('tabs.profile.settings-visible', 'tabs', 'profile', 'settings-visible', [pubkyMask]),
  meta('tabs.profile.sign-out', 'tabs', 'profile', 'sign-out', [pubkyMask]),
  meta('tabs.profile.debug', 'tabs', 'profile', 'debug', [pubkyMask]),
  meta('stack.thread.loading', 'stack', 'thread', 'loading', [pubkyMask]),
  meta('stack.thread.empty', 'stack', 'thread', 'empty', [pubkyMask]),
  meta('stack.thread.populated', 'stack', 'thread', 'populated', [pubkyMask]),
  meta('stack.thread.send-disabled', 'stack', 'thread', 'send-disabled', [pubkyMask]),
  meta('stack.thread.sending', 'stack', 'thread', 'sending', [pubkyMask]),
  meta('stack.thread.failed', 'stack', 'thread', 'failed', [pubkyMask]),
  meta('stack.thread.delivered-read', 'stack', 'thread', 'delivered-read', [pubkyMask]),
  meta('stack.thread.messaging-cta', 'stack', 'thread', 'messaging-cta', [pubkyMask]),
  meta('stack.thread.payment-pending', 'stack', 'thread', 'payment-pending', [pubkyMask]),
  meta('stack.thread.payment-accepted', 'stack', 'thread', 'payment-accepted', [pubkyMask]),
  meta('stack.thread.payment-expired', 'stack', 'thread', 'payment-expired', [pubkyMask]),
  meta('stack.thread.payment-claimed', 'stack', 'thread', 'payment-claimed', [pubkyMask]),
  meta('stack.thread.payment-verified', 'stack', 'thread', 'payment-verified', [pubkyMask]),
  meta('stack.thread.attach-uploading', 'stack', 'thread', 'attach-uploading', [pubkyMask]),
  meta('stack.thread.attach-failed', 'stack', 'thread', 'attach-failed', [pubkyMask]),
  meta('stack.thread.attach-image', 'stack', 'thread', 'attach-image', [pubkyMask]),
  meta('stack.thread.attach-backup', 'stack', 'thread', 'attach-backup', [pubkyMask]),
  meta('stack.composer.sheet', 'stack', 'composer', 'sheet'),
  meta('stack.thread.tip-collapsed', 'stack', 'thread', 'tip-collapsed', [pubkyMask]),
  meta('stack.thread.tip-empty', 'stack', 'thread', 'tip-empty', [pubkyMask]),
  meta('stack.thread.tip-expiry', 'stack', 'thread', 'tip-expiry', [pubkyMask]),
  meta('stack.payment.compose-idle', 'stack', 'payment', 'compose-idle', [pubkyMask]),
  meta('stack.payment.compose-amount', 'stack', 'payment', 'compose-amount', [pubkyMask]),
  meta('stack.payment.compose-reference', 'stack', 'payment', 'compose-reference', [pubkyMask]),
  meta('stack.payment.compose-busy', 'stack', 'payment', 'compose-busy', [pubkyMask]),
  meta('stack.payment.review', 'stack', 'payment', 'review', [pubkyMask]),
  meta('tabs.requests.empty', 'tabs', 'requests', 'empty', [pubkyMask]),
  meta('tabs.requests.populated', 'tabs', 'requests', 'populated', [pubkyMask]),
  meta('tabs.requests.busy', 'tabs', 'requests', 'busy', [pubkyMask]),
  meta('tabs.settings.default', 'tabs', 'settings', 'default'),
  meta('tabs.settings.mesh-on', 'tabs', 'settings', 'mesh-on'),
  meta('tabs.settings.telemetry-on', 'tabs', 'settings', 'telemetry-on'),
  meta('tabs.settings.backup-busy', 'tabs', 'settings', 'backup-busy'),
  meta('tabs.settings.recovery-shown', 'tabs', 'settings', 'recovery-shown', [authUrlMask, recoveryMask]),
  meta('tabs.settings.restore-ok', 'tabs', 'settings', 'restore-ok'),
  meta('tabs.settings.restore-err', 'tabs', 'settings', 'restore-err'),
  meta('tabs.settings.enable-row', 'tabs', 'settings', 'enable-row'),
  meta('tabs.settings.liveproof-idle', 'tabs', 'settings', 'liveproof-idle'),
  meta('tabs.settings.liveproof-running', 'tabs', 'settings', 'liveproof-running'),
  meta('tabs.settings.liveproof-ok', 'tabs', 'settings', 'liveproof-ok'),
  meta('tabs.settings.liveproof-fail', 'tabs', 'settings', 'liveproof-fail'),
  meta('overlay.attach.alert', 'overlay', 'attach', 'alert'),
  meta('overlay.permission.alert', 'overlay', 'permission', 'alert'),
  meta('overlay.wallet.alert', 'overlay', 'wallet', 'alert'),
  meta('overlay.e2e-hud.success', 'overlay', 'e2e-hud', 'success'),
  meta('overlay.e2e-hud.error', 'overlay', 'e2e-hud', 'error'),
  meta('overlay.sign-out.alert', 'overlay', 'sign-out', 'alert'),
  meta('chrome.tab-bar.focused', 'chrome', 'tab-bar', 'focused'),
  meta('chrome.tab-bar.unfocused', 'chrome', 'tab-bar', 'unfocused'),
  meta('a11y.font-scale.two', 'a11y', 'font-scale', 'two'),
  meta('tabs.contacts.content-empty', 'tabs', 'contacts', 'content-empty', [pubkyMask]),
  meta('tabs.contacts.content-populated', 'tabs', 'contacts', 'content-populated', [pubkyMask]),
  meta('tabs.contacts.content-offline', 'tabs', 'contacts', 'content-offline', [pubkyMask]),
  meta('tabs.message-requests.empty', 'tabs', 'message-requests', 'empty', [pubkyMask]),
  meta('tabs.message-requests.populated', 'tabs', 'message-requests', 'populated', [pubkyMask]),
  meta('tabs.settings.recovery-gate', 'tabs', 'settings', 'recovery-gate', [authUrlMask, recoveryMask]),
]);

export function catalogMetaById(id: string): VrtCatalogMeta {
  const entry = VRT_CATALOG_META.find(item => item.id === id);
  if (!entry) {
    throw new Error(`Unknown VRT catalog id: ${id}`);
  }
  return entry;
}

